name: maintenance_app
description: "Une application de gestion de maintenance industrielle."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  # Pour le stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Pour la gestion de l'état et l'injection de dépendances
  provider: ^6.1.1
  get_it: ^7.6.7

  # Pour formater les dates
  intl: ^0.20.2

  # Pour les graphiques du dashboard
  fl_chart: ^0.66.2

  # Pour générer des ID uniques
  uuid: ^4.3.3

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  syncfusion_flutter_calendar: ^30.1.38
  printing: ^5.14.2
  pdf: ^3.11.3
  lottie: ^3.3.1
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Outils pour la génération de code Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/

# ... vos autres configurations (dependencies, flutter, etc.)

# AJOUTEZ CETTE SECTION COMPLÈTE À LA FIN DU FICHIER
flutter_launcher_icons:
  # --- Configuration pour le Web ---
  web:
    generate: true # Active la génération pour le web
    image_path: "assets/logo2_1024.jpg" # Chemin vers votre icône source
    background_color: "#0175C2" # Couleur de fond pour les tuiles (tiles)
    theme_color: "#0175C2" # Couleur du thème

  # --- Configuration pour Windows (optionnel) ---
  windows:
    generate: true
    image_path: "assets/logo2_1024.jpg"
    icon_size: 48 # Taille de l'icône .ico

  # --- Configuration pour Android/iOS (optionnel) ---
  # Vous pouvez laisser cette section si vous prévoyez de faire une app mobile
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2_1024.jpg"
  min_sdk_android: 21 #